# Use a specific version for better stability
FROM node:18 AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

COPY ./src/protos ./src/protos
# Build the application
RUN pnpm build

FROM node:18 AS production

WORKDIR /app

RUN npm install -g pnpm

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/src/protos ./src/protos

EXPOSE 3001

CMD ["pnpm", "start:prod"]
