# Dockerfile for NestJS (server)
FROM node:latest

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

EXPOSE 3001

CMD ["pnpm", "start:prod"]
