# Use a specific Node.js version for better consistency
FROM node:18

RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install --frozen-lockfile


COPY . .

RUN pnpm build

EXPOSE 3001

CMD ["pnpm", "start:dev"]
