// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.28.0
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

/** Define the User message */
export interface User {
  id: string;
}

/** Define request and response messages */
export interface RegisterRequest {
  name: string;
  email: string;
  password: string;
  phoneNumber: string;
  address: string;
}

export interface RegisterResponse {
  activationToken: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  user: User | undefined;
  accessToken: string;
  refreshToken: string;
  error: ErrorResponse | undefined;
}

export interface ActivationRequest {
  activationToken: string;
  activationCode: string;
}

export interface ActivationResponse {
  message: string;
}

export interface LogoutResponse {
  message: string;
}

export interface GetLoggedInUserResponse {
  user: User | undefined;
  accessToken: string;
  refreshToken: string;
}

export interface EmptyRequest {
}

export interface UserListResponse {
  users: User[];
}

export interface RoleRequest {
  role: string;
}

export interface RoleResponse {
  permissions: string[];
}

export interface ForgotRequest {
  email: string;
}

export interface ForgotResponse {
  forgotPasswordToken: string;
  message: string;
}

export interface ResetRequest {
  password: string;
  forgotPasswordToken: string;
}

export interface ResetResponse {
  user: User | undefined;
  message: string;
}

export interface ChangeRequest {
  password: string;
  changePasswordToken: string;
}

export interface ChangeResponse {
  user: User | undefined;
  updatedPassword: string;
  message: string;
}

export interface ErrorResponse {
  message: string;
}

/** Define the gRPC service */

export interface UserServiceClient {
  register(request: RegisterRequest): Observable<RegisterResponse>;

  login(request: LoginRequest): Observable<LoginResponse>;

  activateUser(request: ActivationRequest): Observable<ActivationResponse>;

  getAllUser(request: EmptyRequest): Observable<UserListResponse>;

  logout(request: EmptyRequest): Observable<LogoutResponse>;

  getLoggedInUser(request: EmptyRequest): Observable<GetLoggedInUserResponse>;

  getRolePermissions(request: RoleRequest): Observable<RoleResponse>;

  forgotPassword(request: ForgotRequest): Observable<ForgotResponse>;

  resetPassword(request: ResetRequest): Observable<ResetResponse>;

  changePassword(request: ChangeRequest): Observable<ChangeResponse>;
}

/** Define the gRPC service */

export interface UserServiceController {
  register(request: RegisterRequest): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  activateUser(
    request: ActivationRequest,
  ): Promise<ActivationResponse> | Observable<ActivationResponse> | ActivationResponse;

  getAllUser(request: EmptyRequest): Promise<UserListResponse> | Observable<UserListResponse> | UserListResponse;

  logout(request: EmptyRequest): Promise<LogoutResponse> | Observable<LogoutResponse> | LogoutResponse;

  getLoggedInUser(
    request: EmptyRequest,
  ): Promise<GetLoggedInUserResponse> | Observable<GetLoggedInUserResponse> | GetLoggedInUserResponse;

  getRolePermissions(request: RoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  forgotPassword(request: ForgotRequest): Promise<ForgotResponse> | Observable<ForgotResponse> | ForgotResponse;

  resetPassword(request: ResetRequest): Promise<ResetResponse> | Observable<ResetResponse> | ResetResponse;

  changePassword(request: ChangeRequest): Promise<ChangeResponse> | Observable<ChangeResponse> | ChangeResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "activateUser",
      "getAllUser",
      "logout",
      "getLoggedInUser",
      "getRolePermissions",
      "forgotPassword",
      "resetPassword",
      "changePassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
