
FROM node:18 AS build


WORKDIR /app


COPY package.json pnpm-lock.yaml ./


RUN npm install -g pnpm && pnpm install --frozen-lockfile


COPY . .


RUN pnpm build


FROM node:18 AS production


WORKDIR /app


RUN npm install -g pnpm


COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

# Expose the port based on the specific API
EXPOSE 4000

# Start the application in production mode
CMD ["pnpm", "start:prod"]
